config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :task
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board_and_task

  def new
    @comment = @task.comments.build
  end

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user_id = current_user.id # コメントのuser_idフィールドに現在のユーザーのIDを設定しています。
    if @comment.save
      redirect_to board_task_path(board_id: @board.id, id: @task.id), notice: 'コメントを投稿しました'
    else
      flash.now[:error] = 'コメントの投稿に失敗しました'
      render :new
    end
  end

  private
  def set_board_and_task
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:task_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/new.html.haml
.container
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message

  = form_with(model: [@board, @task, @comment], url: board_task_comments_path(@comment.task.board_id, @comment.task_id), local: true) do |f|
    .new_board_title
      %h2 New Comment
    .new_content_area
      = f.text_area :content
    .new_board_button
      = f.submit 'Submit', class: 'button'