config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  time_limit :datetime
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#
class Task < ApplicationRecord
  has_one_attached :eyecatch

  validates :title, presence:true
  validates :title, length: { minimum: 2, maximum: 100}
  validates :title, format: { with: /\A(?!\@)/ }

  validates :content, presence:true
  validates :content, length: {minimum: 5, maximum: 100}
  validates :content, uniqueness: true

  belongs_to :user
  belongs_to :board
  has_many :comments, dependent: :destroy

  def comment_count
    comments.count
  end

  def last_three_commenters
    comments.last(3).map(&:user).uniq.last(3)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @board = Board.find(params[:board_id])
    @tasks = @board.tasks.all
  end

  def show
    @task = Task.find(params[:id])
    @comments = @task.comments
  end

  def new
    @task = current_user.tasks.build(board_id: params[:board_id])
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.board_id = params[:board_id]
    if @task.save
      redirect_to board_tasks_path(params[:board_id]), notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if  @task.update(task_params)
      redirect_to board_task_path(@task), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    board = task.board
    task.destroy!
    redirect_to board_tasks_path(board), notice: '削除に成功しました'
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :eyecatch)
  end
end

app/views/tasks/edit.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  .new_board_title
    %h2 New Card
  = form_with(model: @task, url: board_task_path(@task), method: 'put', local:true) do |f|
    .new_board_area
      = f.label :eyecatch, 'Eyecatch'
    .new_board_label
      = f.file_field :eyecatch, class: 'file'
    .new_board_area
      .new_board_label
        = f.label :title, 'Name'
      %div
        = f.text_field :title, class: 'text'
    .new_board_area
      .new_board_label
        = f.label :content, 'Description'
      %div
        = f.text_area :content
    .new_board_button
      = f.submit 'Submit', class: 'button'

app/views/tasks/index.html.haml
= form_with(model: @task, url: board_tasks_path(@board), local:true) do |f|
  .container
    %h2 Brackets
    - @tasks.each do |task|
      = link_to board_task_path(board_id: @board, id: task.id) do
        .card
          - if task.eyecatch.attached?
            .card_image
              = image_tag task.eyecatch
          .card_task_title
            = task.title
          .card_content
            = task.content
          .card_detail
            = image_tag task.user.avatar_image
            - task.last_three_commenters.each do |user|
              = image_tag user.avatar_image, class: 'card_commenter_icon'
          .card_comments_count
            %span= task.comment_count
            = image_tag 'message-square-outline.svg'
    = link_to new_board_task_path do
      .new_card
        .new_card_title
          %p + Add new card

app/views/tasks/new.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  .new_board_title
    %h2 New Card
  = form_with(model: @task, url: board_tasks_path, method: 'post', local:true) do |f|
    .new_board_area
      = f.label :eyecatch, 'Eyecatch'
    .new_board_label
      = f.file_field :eyecatch, class: 'file'
    .new_board_area
      .new_board_label
        = f.label :title, 'Name'
      %div
        = f.text_field :title, class: 'text'
    .new_board_area
      .new_board_label
        = f.label :content, 'Description'
      %div
        = f.text_area :content
    .new_board_button
      = f.submit 'Submit', class: 'button'

app/views/tasks/show.html.haml
.task
  %h1.task_title= @task.title
  - if user_signed_in? && current_user.has_create?(@task)
    .task_detail_actions
      .dropdown
        = image_tag 'action.svg', class: 'dropbtn'
        .dropdown-content.mini
          = link_to 'Edit', edit_board_task_path(@task)
          = link_to 'Delete', board_task_path(@task), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？'}
  - if @task.eyecatch.attached?
    .task_image
      = image_tag @task.eyecatch
  .task_content
    = @task.content
  .comment_title
    %p Comment
  - @comments.each do |comment|
    .task_comment
      .task_comment_avatar
        = image_tag comment.user.avatar_image, class: 'header_avatar dropbtn'
      %p= comment.content
  = link_to new_board_task_comment_path(task_id: @task.id) do
    .new_comment_card
      .new_comment_card_title
        %p + Add new comment