config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  validates :title, presence:true
  validates :title, length: { minimum: 2, maximum: 100}
  validates :title, format: { with: /\A(?!\@)/ }

  validates :content, presence:true
  validates :content, length: {minimum: 5, maximum: 100}
  validates :content, uniqueness: true

  has_many :tasks, dependent: :destroy
  belongs_to :user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @boards = Board.all
  end

  def show
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to root_path(@board), notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if  @board.update(board_params)
      redirect_to board_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def board_params
    params.require(:board).permit(:title, :content)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/views/boards/edit.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, url: board_path(@board), method: 'put', local:true) do |f|
    .new_board_area
      .new_board_label
        = f.label :title, 'Name'
      %div
        = f.text_field :title, class: 'text'
    .new_board_area
      .new_board_label
        = f.label :content, 'Description'
      %div
        = f.text_area :content
    .new_board_button
      = f.submit 'Submit', class: 'button'

app/views/boards/index.html.haml
.container
  %h2 All Boards
  - @boards.each do |board|
    = render 'commons/board', board: board
  = link_to new_board_path do
    .new_card
      .new_card_title
        %p + Add new board

app/views/boards/new.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  .new_board_title
    %h2 New Board
  = form_with(model: @board, url: boards_path, method: 'post', local:true) do |f|
    .new_board_area
      .new_board_label
        = f.label :title, 'Name'
      %div
        = f.text_field :title, class: 'text'
    .new_board_area
      .new_board_label
        = f.label :content, 'Description'
      %div
        = f.text_area :content
    .new_board_button
      = f.submit 'Submit', class: 'button'

app/views/boards/show.html.haml
.container
  %h2 Brackets
  - @tasks.each do |task|
    .card
      .card_content
        .card_title
          = task.title
        .card_text
          = task.content

  = link_to new_board_path do
    .new_card
      .new_card_title
        %p + Add new card